# DECISION TREE CLASSIFIER FROM SKLEARN- LEARN ON IRIS DATASETS:

In [28]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

# 1. Load the data

In [29]:
iris = datasets.load_iris()

In [30]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# 2. Features and target are in diffrent

In [31]:
x = iris.data
y = iris.target
x.ndim,y.ndim

(2, 1)

# 3. Split the data into training and testing data

In [32]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

# 4. Standardize the Data

In [33]:
sc = StandardScaler()
x_train_std = sc.fit_transform(x_train)
x_test_std = sc.fit_transform(x_test)

In [34]:
x_train_std

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.55797625e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.98410911e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12707506e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31530348e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38416753e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -8.01118523e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31530348e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.86933568e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41436341e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.64126001e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.55797625e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
      

In [35]:
x_test_std

array([[ 0.12564197, -0.62989827,  0.88070613,  1.81979323],
       [ 0.42404164, -2.01082908,  0.21500059, -0.1846167 ],
       [-0.32195754,  2.59227364, -1.35848522, -1.32999381],
       [ 2.36363949, -0.39974313,  1.60693035,  0.9607604 ],
       [-1.06795671,  0.75103255, -1.29796654, -1.32999381],
       [ 0.87164114,  0.52087741,  1.4253743 ,  1.96296536],
       [-1.06795671,  0.98118769, -1.41900391, -1.18682167],
       [ 1.46844048,  0.06056714,  0.63863139,  0.53124399],
       [ 1.61764032, -0.62989827,  0.69915007,  0.38807185],
       [ 0.57324147, -0.62989827,  0.21500059,  0.24489971],
       [ 0.57324147, -1.09020854,  1.18329955,  0.38807185],
       [ 1.02084098,  0.29072228,  0.51759402,  0.53124399],
       [ 0.57324147, -0.62989827,  0.63863139,  0.10172757],
       [ 1.17004081, -0.62989827,  0.5781127 ,  0.53124399],
       [ 0.57324147, -0.39974313,  0.63863139,  0.38807185],
       [-1.21715655,  1.21134282, -1.35848522, -1.47316594],
       [ 0.42404164, -0.

# 5. Choose Algo & Set the hyperparametres

In [36]:
tree = DecisionTreeClassifier(criterion='entropy',random_state=0)

In [37]:
tree

DecisionTreeClassifier(criterion='entropy', random_state=0)

# 6. Train the model

In [38]:
tree.fit(x_train_std,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# 7. Make the prediction using the model

In [39]:
pred = tree.predict(x_test_std)

In [40]:
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [41]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [42]:
np.where(pred!=y_test)

(array([8], dtype=int64),)

In [43]:
pred[8],y_test[8]

(2, 1)

In [44]:
print('ACCURACY :', accuracy_score(y_test,pred))

ACCURACY : 0.9736842105263158


# CONFUSION MATRIX

In [45]:
from sklearn.metrics import confusion_matrix

In [46]:
con = confusion_matrix(y_test,pred)

In [47]:
con

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [48]:
import graphviz
from sklearn import tree